Test find_cabal(): Find a `cabal` executable
This uses what the search path gives us, if anything, and otherwise
finds one installed by `ghcup`. Possibly further searching could be
done, but there are no obvious other places to look. (If there are
Stack-installed tools, these don't include `cabal` because Stack has
that built-in to itself.)

We expect that users concerned about path polution will not have
`cabal` in their path; we should provide a way to easily give these
users an alias or shell function to run the `cabal` we found.

Cabal is not yet used; we still build with Stack.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -17,6 +17,7 @@ fail() {
     echo 1>&2 "FAILED exitcode=$ec ($(elapsed)s)"
     exit $ec
 }
+warn()  { echo 1>&2 'Warning:' "$@"; }
 
 since_timestamp() {
     local tsdir="$BUILDDIR/timestamp"
@@ -101,6 +102,37 @@ install_hpack() {
     url='https://github.com/sol/hpack/releases/download/0.38.2/hpack_linux.gz'
     curl -sSL "$url" | gunzip > "$TOOLBIN/hpack"
     chmod +x "$TOOLBIN/hpack"
+}
+
+#   This sets $cabal to the `cabal` executable we will use for builds.
+#   We assume that if there's a `cabal` available in $PATH, regardless
+#   of version, that's the one we should use because that's what the
+#   developer will be using at the command line. (We warn if the version
+#   is lower than we would like.) Otherwise we examine what's available
+#   in ~/.ghcup/bin/ and take either the default version set there, or
+#   the highest version available.
+find_cabal() {
+    declare -g cabal
+    local  minver=3.11      # Warn if cabal we use is less than this version.
+    #   The `find` below doesn't do a proper numeric sort, but it produces
+    #   a good-enough result that it's not worth splitting on '-' and again
+    #   on '.' to try to get the very latest minor release.
+    local ghcup_bin="$HOME/.ghcup/bin"
+    local exe
+    for exe in                      \
+        cabal                       \
+        "$ghcup_bin/cabal"          \
+        $([[ -d $ghcup_bin ]]       \
+            && find "$ghcup_bin" -name cabal-\* \
+            | sort -r) \
+    ; do
+        "$exe" --numeric-version >/dev/null 2>&1 || continue
+        local ver=$("$exe" --numeric-version)
+        [[ $ver < $minver ]] && warn "version $ver < $minver for $exe"
+        cabal="$exe"
+        return 0
+    done
+    die 3 'Cannot find a `cabal` executable. Install one with ghcup?'
 }
 
 #   Liquid Haskell needs an SMT solver; we use Z3 as suggested, in part
@@ -204,6 +236,7 @@ echo '━━━━━ Development Tools'
 install_z3
 install_hpack
 (cd "$PROJDIR" && hpack --silent)
+find_cabal   # sets global $cabal
 install_stack
 #   Ensure toolchain is installed before checking for ghc core, because
 #   otherwise the ghc core check will silently install GHC etc., giving
