exe/ShowExports: `show-exports FILE.hs` lists explicit exports
This gets us a little way towards being able to create a "generic
evaluator" command-line program that can run arbitrary code without us
having to hand-code the imports and names into the command-line
program. Given a source file, it prints the module name and the
explicit exports. (If no export list is given, it does not, as Haskell
does, assume that all top-level definitions are exported, though we
could do further parsing to implement this.)

This uses the haskell-src-exts package, which is a fairly lightweight
parser that doesn't handle preprocessors such as Template Haskell. for
that, we'd probably need to move to parsing using ghc-lib-parser or
similar. But since we also need to parse only the head information of the
module (in fact, just the module name and export list, not even the
imports), we might be able to get around the need for something more
complex by using the haskell-src-exts's lazy parser and just letting it
stop at anything it can't handle after the module name and export list.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -443,28 +443,32 @@ test_exe() {
 }
 
 test_executables() {
-    local exe=$(.build/tool/bin/cabal list-bin hand-run)
-
-    test_exe "$exe" \
-        'State {k = [], store = fromList [("n",0),("sum",6)]}' \
-        imp sum 3
-
-    test_exe "$exe" \
-        'State {k = [KI_Stmts (Block EmptyBlock)], store = fromList [("n",0),("sum",10)]}' \
-        optimp sum 4
-
-    test_exe "$exe" \
-        "$(printf '15\nState {k = [], store = fromList [("n",0),("sum",15)]}')" \
-        imp_io sum_io < <(echo 5)
+    local hand_run=$($TOOLBIN/cabal list-bin hand-run)
 
     #   Generate error on bad args.
     vecho 1 '• Testing bad arguments'
     local ec=0
-    "$exe" BAD_ARGUMENT >/dev/null 2>&1 || ec=$?
+    "$hand_run" BAD_ARGUMENT >/dev/null 2>&1 || ec=$?
     [[ $ec -eq 1 ]] || {
-        echo "hand-run '$(basename "$exe")' badarg did not fail (ec=$ec)"
+        echo "hand-run '$(basename "$hand_run")' badarg did not fail (ec=$ec)"
         false || fail
     }
+
+    test_exe "$hand_run" \
+        'State {k = [], store = fromList [("n",0),("sum",6)]}' \
+        imp sum 3
+
+    test_exe "$hand_run" \
+        'State {k = [KI_Stmts (Block EmptyBlock)], store = fromList [("n",0),("sum",10)]}' \
+        optimp sum 4
+
+    test_exe "$hand_run" \
+        "$(printf '15\nState {k = [], store = fromList [("n",0),("sum",15)]}')" \
+        imp_io sum_io < <(echo 5)
+
+    test_exe $($TOOLBIN/cabal list-bin show-exports) \
+        'KTutImp_Program: sum_imp, divide_imp, div0_imp, sum_imp_io' \
+        $PROJDIR/program/KTutImp_Program.hs
 }
 
 ####################################################################
