Test,doc/core: Add Development Tools installation section with ghc-core
Per the comments, this can't be done as part of {package,stack}.yaml
but instead needs to be done with "manual" stack commands.

Start documenting how to use ghc-core in doc/core.md.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -93,6 +93,22 @@ z3 --version >/dev/null 2>&1 || {
         || die 3 'Cannot `apt install z3`; try your own package manager?'
 }
 
+echo '━━━━━ Development Tools'
+#   Some development tools available from Stackage are a binary we run,
+#   rather than a library we use, and we appear to be unable to add those
+#   sorts of things to our {package,stack}.yaml. This adds these to the
+#   current project to make them available via `stack exec`. (They are
+#   actually available globally for any Stack-using project using the same
+#   resolver and, where compiler-specific, compiler version.)
+pcre-config --version >/dev/null 2>&1 || {
+    echo '───── Installing libpcre3-dev'
+    #   XXX Seems this wants to produce two dozen or more lines of output
+    #   no matter what we do to try to make it quiet.
+    sudo apt -q -q -qq install -y -q -q -qq libpcre3-dev \
+        || die 3 'Cannot `apt install libpcre3-dev`; try your own package manager?'
+}
+stack build ghc-core
+
 echo '━━━━━ Build'
 cd "$PROJDIR"
 #   We want to regularly build with the latest versions of our dependencies
