bench/Bench: Add Haskell benchmark run and h/k parameter to choose
Though currently Stack's dependency ensures that we complete the build
in less than a second if nothing's changed, we allow use of the `-s`
(skip build) option with the Haskell benchmark anyway, in case we add
time-consuming unit tests later.

diff --git a/bench/Bench b/bench/Bench
--- a/bench/Bench
+++ b/bench/Bench
@@ -12,27 +12,52 @@ trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
 
 die() { ec=$1; shift; echo "$@"; exit $ec; }
 
+####################################################################
+
+benchmark_h() {
+    echo "───── build/test"
+    $skip_compile \
+        && { echo "WARNING: build/test skipped"; } \
+        || ./Test
+    echo "───── run"
+    time $(stack path --local-install-root)/bin/benchmark
+}
+
+benchmark_k() {
+    mkdir -p "$BUILDDIR"
+    echo "───── kompile"
+    $skip_compile \
+        && { echo "WARNING: kompile skipped"; } \
+        || time kompile -o "$BUILDDIR" bench/imp.k
+    echo "───── krun"
+    #   We need only the .kore file (parsed program and initial state);
+    #   `--depth 0` stops without taking any steps, printing the initial state.
+    time krun -d "$BUILDDIR" bench/sum.imp --depth 0 \
+        --output kore > "$BUILDDIR"/sum.kore
+    echo "───── interpreter"
+    (   cd "$BUILDDIR"
+        #   Iteration count hard-coded into sum.imp.
+        time ./interpreter ./sum.kore -1 sum.output
+    )
+}
+
+####################################################################
+
 PROJDIR=$(command cd "$(dirname "$0")/.." && pwd -P)
 BUILDDIR="$PROJDIR"/.build/bench/imp-kompiled
 
 skip_compile=false
-while [[ $# -gt 0 ]]; do case "$1" in
+while [[ $# -gt 0 ]]; do case "$1" in                   # options
     -s|--skip-kompile)  shift; skip_compile=true;;
-    *)                  die 2 "Unknown argument: $1";;
+    --)                 shift; break;;
+    -*)                 die 2 "Unknown option: $1";;
+    *)                  break;;
 esac; done
+[[ $# -eq 1 ]] || die 2 "error: One parameter required."
 
 command cd "$PROJDIR"
-mkdir -p "$BUILDDIR"
-echo "───── kompile"
-$skip_compile \
-    && { echo "WARNING: skipped"; } \
-    || time kompile -o "$BUILDDIR" bench/imp.k
-echo "───── krun"
-#   We need only the .kore file (parsed program and initial state);
-#   `--depth 0` stops without taking any steps, printing the initial state.
-time krun -d "$BUILDDIR" bench/sum.imp --depth 0 \
-    --output kore > "$BUILDDIR"/sum.kore
-echo "───── interpreter"
-(   cd "$BUILDDIR"
-    time ./interpreter ./sum.kore -1 sum.output
-)
+case "$1" in                                            # parameters
+    k)  benchmark_k;;
+    h)  benchmark_h;;
+    *)  die 2 "Unknown benchmark type '$1': use 'h'=Haskell, 'k'=K"
+esac
